### ISSUE TITLE
Introduce a ui element to select different  Liquidity pools than bark

### ISSUE THREAD

**Issue by allquantor** [Autonomous-Finance/dca-agent#5]
We would like to amplify that agnostic to the liquidity pools we are working with. They don't have to exist now, but it should be visible that we have them. Can you come up with an Multiselect UI element that will make it clear. Lets add an option for "Global-RFQ" standing for a global Request-For-Quote system, indicating that we will have it. However, selecting it should have no effect.

![image](https://github.com/Autonomous-Finance/dca-bot/assets/5374259/ec46f87c-297a-473c-ae8c-fb486685e153)

**Comment by dvinubius** [comment]
Done
